name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
          cache: 'go'
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev  

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install -v github.com/lc/gau/v2/cmd/gau@latest
          go install -v github.com/tomnomnom/waybackurls@latest
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          #go install -v github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
          
        shell: bash
        
#       - name: Cache ProjectDiscovery tools
#         uses: actions/cache@v3
#         with:
#           cache: 'tools'
#           path: /home/runner/go
#           key: ${{ runner.os }}-go-tools

      - name: Running SubFinder for passive DNS enumeration
        run: |
          rm -rf *_*.txt
          subfinder -dL domains.txt -config config/subfinder-config.yaml -o active_subdomains.txt
        shell: bash

      # - name: Running dnsx for valid DNS filtering 
      #   run: |
      #     dnsx -l passive_subdomains.txt -t 50 | tee -a active_subdomains.txt
      #     sort -u active_subdomains.txt
      #   shell: bash
      
      # - name: Scaning all ports...
      #   continue-on-error: true
      #   # timeout-minutes: 30
      #   run: |
      #     #nuclei -tags log4j -l active_urls.txt -bs 100 -c 50 -rl 300 -nc | tee nuclei_output.txt
      #     #naabu -l passive_subdomains.txt -p 1-65535 -c 10000 | httpx -title -t 230 | tee naabu.txt
          
      #     naabu -l active_subdomains.txt -p 1-65535 -c 10000 -o naabu.txt
      #     cat naabu.txt >> active_subdomains.txt | sort -u 
          


      - name: Running httpx for HTTP webservers probbing
        run: |
          #httpx -l active_subdomains.txt -title -t 230
          httpx -l active_subdomains.txt -t 730 -mc 100,101,200,201,204,301,302,304,400,403,404,500,502,503 -o passive_subdomains.txt
          httpx -l passive_subdomains.txt -title -t 430
        shell: bash

      - name: Getting all urls...
        continue-on-error: true
        timeout-minutes: 340
        run: |
        
          #nuclei -tags log4j -l active_urls.txt -bs 100 -c 50 -rl 300 -nc | tee nuclei_output.txt
          #naabu -l passive_subdomains.txt -p 1-65535 -c 2000 | httpx -title -t 230 | tee naabu.txt
          #naabu -l passive_subdomains.txt -p 1-65535 -c 2000 | tee naabu.txt 
          
          # naabu -l passive_subdomains.txt -tp 100 -c 3000 | tee naabu.txt
          # cat naabu.txt | gau --subs --blacklist png,jpg,gif,css --o gl.txt
          # cat naabu.txt | waybackurls > way_urls.txt | tee -a gl.txt

          cat passive_subdomains.txt | gau --subs --blacklist png,jpg,gif,css | tee g_w.txt 
          cat passive_subdomains.txt | waybackurls >> g_w.txt  
          #cat passive_subdomains.txt | waybackurls > way_urls.txt | tee -a g_w.txt  
          
          # sort -u g_w.txt 
          
        shell: bash

      - name: Running NucleiFuzzing...
        timeout-minutes: 340
        continue-on-error: true
        run: |

            git clone https://github.com/projectdiscovery/fuzzing-templates.git
            nuclei -l g_w.txt -t fuzzing-templates -rl 50 -o nuclei_out.txt

      - name: Create local changes
        run: |
          git add *.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "admin@Wg.org"
          git config --global user.name "Wg-team"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
